steps:
      # Checkout v4.0.0
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608

      # Setup Node v4.0.0
      - name: Setup Node
        uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65
        with:
          node-version: '18'
          cache: 'npm'

      - run: npm ci
      - run: npm run build

      # Upload Pages Artifact v3.0.0
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa
        with:
          path: './dist'

      # Deploy Pages v4.0.0
      - name: Deploy
        uses: actions/deploy-pages@d6db90164ad5b118d2d652a80c7514659966df30
        id: deployment
