steps:
      - name: Checkout
        uses: actions/checkout@v4 # <-- This pulls your code into the runner
      
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./docs
